name: Publish Binary Packages

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    permissions:
      packages: write
      contents: read
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Rust toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: false
          components: rustfmt
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ steps.rust_toolchain.outputs.rustc_hash }}-cache
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: packages/dkg-standalone-binary/yarn.lock
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@webb-tools"
      - run: yarn
        working-directory: packages/dkg-standalone-binary
      - run: yarn publish
        working-directory: packages/dkg-standalone-binary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_url: ${{ github.server_url }}
          github_token: ${{ secrets.WEBB_BOT_GH_PAT }}
          branch: ${{ github.ref }}
          force: true
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
