name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}
        - uses: actions/checkout@v2
        
        - name: Check markdown links
          uses: gaurav-nelson/github-action-markdown-link-check@v1
          with:
            use-quiet-mode: 'yes'
            config-file: '.github/workflows/mlc_config.json'

        - name: Check License Header
          uses: apache/skywalking-eyes@main
          with: 
            config: .licenserc.yaml